#!/bin/bash

HOUR=$(date '+%H')
YEAR=$(date '+%Y')
MONTH=$(date '+%m')
MIN=$(date '+%M')

DAY=$(date '+%d')
SEG=$(date '+%S')
MIN2=`expr $MIN + 20`
#HOUR2=`expr $HOUR - 1`

echo $MONTH
echo $MIN
echo $MIN2


data_json_app1=$(curl -X GET 'https://api.newrelic.com/v2/applications/13657517/metrics/data.json' \
     -H 'X-Api-Key:968940418726fb2ee473fb7be41266b29e3cf89b70d334b' -i   \
     -G -d 'names[]=WebTransactionTotalTime/Custom/valorizacion&from='2016'-'$MONTH'-'11'T'12':'20':00+00:00&to='2016'-'$MONTH'-'11'T'12':'30'+00:00&period=150&summarize=false&raw=true' | grep 'metric_data')
    

#echo $data_json_app1| jq -r ".metric_data.metrics[0].timeslices[] |  [.from, .to, .values.average_response_time, .values.calls_per_minute, .values.call_count, .values.min_response_time, .values.max_response_time, .values.average_exclusive_time,.values.average_value, .values.total_call_time_per_minute,.values.requests_per_minute, .values.standard_deviation] | @csv" | sed 's/"//g' > w01.csv
#
#
#IFS=,
#while read col1 col2 col3 col4 col5 col6 col7 col8 col9 col10 col11
#do
#        echo "INSERT INTO W01  VALUES ( '$col1','$col2','$col3','$col4','$col5','$col6','$col7','$col8','$col9','$col10','$col11');"
#done < w01.csv | mysql -u root -pl4titud33 NEW_RELIC ;
##
