#!/bin/bash

HOUR=$(date '+%H')
YEAR=$(date '+%Y')
MONTH=$(date '+%m')
MIN=$(date '+%M')
DAY=$(date '+%d')
SEG=$(date '+%S')
MIN2=`expr $MIN + 30`
HOUR2=`expr $HOUR - 1`


for i in 0 1
do
data_json_app1=$(curl -X GET 'https://api.newrelic.com/v2/applications/13657517/metrics/data.json' \
     -H 'X-Api-Key:968940418726fb2ee473fb7be41266b29e3cf89b70d334b' -i   \
     -G -d 'names[]=Apdex/Custom/certificacion&names[]=Apdex/Custom/valorizacion&from='$YEAR'-'$MONTH'-'$DAY'T'$HOUR2':'$MIN':00+00:00&to='$YEAR'-'$MONTH'-'$DAY'T'$HOUR':'$MIN'+00:00&period=300&summarize=false&raw=true' | grep 'metric_data')

echo $data_json_app1| jq -r ".metric_data.metrics[$i].timeslices[] | [.from, .to, .values.s, .values.t, .values.f,.values.value ]|@csv"| sed 's/"//g'| sed "s/$/,$i/g" >> file_01.csv
done


data_json_app2=$(curl -X GET 'https://api.newrelic.com/v2/applications/13657519/metrics/data.json' \
     -H 'X-Api-Key:968940418726fb2ee473fb7be41266b29e3cf89b70d334b' -i   \
     -G -d 'names[]=Apdex/Custom/certificacion&from='$YEAR'-'$MONTH'-'$DAY'T'$HOUR2':'$MIN':00+00:00&to='$YEAR'-'$MONTH'-'$DAY'T'$HOUR':'$MIN'+00:00&period=300&summarize=false&raw=true' | grep 'metric_data')

echo $data_json_app2| jq -r ".metric_data.metrics[].timeslices[] | [.from, .to, .values.s, .values.t, .values.f,.values.value ]|@csv"| sed 's/"//g'| sed "s/$/,0/g" >> file_02.csv


IFS=,
while read col1 col2 col3 col4 col5 col6 col7 
do
        echo "INSERT INTO APP_01  VALUES ( '$col1','$col2','$col3','$col4','$col5','$col6','$col7');"
done < file_01.csv | mysql -u root -pl4titud33 NEW_RELIC ;


IFS=,
while read col1 col2 col3 col4 col5 col6 col7 
do
        echo "INSERT INTO APP_02 VALUES ( '$col1','$col2','$col3','$col4','$col5','$col6','$col7');"
done < file_02.csv | mysql -u root -pl4titud33 NEW_RELIC ;


rm -f file_0*
                                                                                                                                  
